//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int Id_alumnos { get; set; }
        public Nullable<int> Id_escuela_alumnos { get; set; }
        public string nombre_alumnos { get; set; }
        public string apellidoP_alumnos { get; set; }
        public string apellidoM_alumnos { get; set; }
        public Nullable<System.DateTime> fecha_nac_alumnos { get; set; }
        public Nullable<int> no_lista_alumnos { get; set; }
    
        public virtual Escuelas Escuelas { get; set; }
    }
}
