
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjBlablabla.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Alumnos
{

    public int Id_alumnos { get; set; }

    public Nullable<int> Id_escuela_alumnos { get; set; }

    public string nombre_alumnos { get; set; }

    public string apellidoP_alumnos { get; set; }

    public string apellidoM_alumnos { get; set; }

    public Nullable<System.DateTime> fecha_nac_alumnos { get; set; }

    public Nullable<int> no_lista_alumnos { get; set; }



    public virtual Escuelas Escuelas { get; set; }

}

}
