//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctFrasesSilabitos
    {
        public int Id { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string orden { get; set; }
        public Nullable<short> acomodo { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
