//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctFrasesSilabitos
    {
        public int Id { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string orden { get; set; }
        public Nullable<short> acomodo { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> nivel { get; set; }
    }
}
