//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctFrases
    {
        public int Id { get; set; }
        public string enun1 { get; set; }
        public string enun2 { get; set; }
        public short correcta { get; set; }
        public string opcion1 { get; set; }
        public string opcion2 { get; set; }
        public string opcion3 { get; set; }
    }
}
