//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctFrases
    {
        public int Id { get; set; }
        public string enun1 { get; set; }
        public string enun2 { get; set; }
        public short correcta { get; set; }
        public string opcion1 { get; set; }
        public string opcion2 { get; set; }
        public string opcion3 { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> juego { get; set; }
    }
}
