//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctFrasesBosque
    {
        public int Id { get; set; }
        public string Frase { get; set; }
        public string Opcion1 { get; set; }
        public string Opcion2 { get; set; }
        public Nullable<bool> Correcta { get; set; }
        public byte Nivel { get; set; }
        public bool Estado { get; set; }
    }
}
