//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    public partial class BlablablaSitioEntities : DbContext
    {
        public BlablablaSitioEntities()
            : base("name=BlablablaSitioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ctFrases> ctFrases { get; set; }
        public DbSet<ctFrasesSilabitos> ctFrasesSilabitos { get; set; }
        public DbSet<Alumnos> Alumnos { get; set; }
        public DbSet<Escuelas> Escuelas { get; set; }
    
        public virtual int sp_InactivaFrases(Nullable<int> tipo)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InactivaFrases", tipoParameter);
        }
    }
}
