//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuelas
    {
        public Escuelas()
        {
            this.Alumnos = new HashSet<Alumnos>();
        }
    
        public int Id_escuelas { get; set; }
        public string nombre_escuelas { get; set; }
        public string grado_escuelas { get; set; }
        public string grupo_escuelas { get; set; }
    
        public virtual ICollection<Alumnos> Alumnos { get; set; }
    }
}
