//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuelas
    {
        public Escuelas()
        {
            this.Alumnos = new HashSet<Alumnos>();
        }
    
        public int Id_escuelas { get; set; }
        public string nombre_escuelas { get; set; }
        public string grado_escuelas { get; set; }
        public string grupo_escuelas { get; set; }
    
        public virtual ICollection<Alumnos> Alumnos { get; set; }
    }
}
