//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        public Escuela()
        {
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
    
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
