//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado
    {
        public Grado()
        {
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int ID { get; set; }
        public int Grado1 { get; set; }
        public string Descripción { get; set; }
    
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
