//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBlablabla.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public int IdEscuela { get; set; }
        public int NLista { get; set; }
        public int Grado { get; set; }
        public string Grupo { get; set; }
        public int IdJuego { get; set; }
        public int Nivel { get; set; }
        public int Consecutivo { get; set; }
        public Nullable<int> Correcto { get; set; }
        public Nullable<int> Incorrecto { get; set; }
    }
}
